# Generated by Django 6.0.1 on 2026-03-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
