# Generated by Django 6.0.1 on 2026-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork', '0002_userprofile_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration_no', models.CharField(max_length=15, unique=True)),
                ('project', models.FileField(upload_to='project/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
