# Generated by Django 6.0.1 on 2026-03-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork', '0003_registration_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='project',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_no',
        ),
        migrations.AddField(
            model_name='registration',
            name='file_upload',
            field=models.FileField(default='', upload_to='files/'),
            preserve_default=False,
        ),
    ]
