# Generated by Django 6.0.1 on 2026-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork', '0004_remove_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='file_upload',
            field=models.FileField(upload_to='project/'),
        ),
    ]
